# Generated by Django 2.2.5 on 2019-09-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=20, verbose_name='Логин')),
                ('Password', models.CharField(max_length=128, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person', models.CharField(max_length=255, verbose_name='ФИО сотрудника')),
                ('SerialPassport', models.IntegerField(verbose_name='Серия паспорта')),
                ('NumberPassport', models.IntegerField(verbose_name='Номер паспорта')),
                ('Education', models.TextField(verbose_name='Образование')),
                ('Tags', models.TextField(verbose_name='Теги')),
            ],
        ),
    ]
