# Generated by Django 2.2.5 on 2019-09-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=20, verbose_name='Логин')),
                ('Password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('Type', models.IntegerField(verbose_name='Тип пользователя')),
            ],
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
