# Generated by Django 2.2.5 on 2019-09-28 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hakapp', '0002_auto_20190928_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True, verbose_name='Название тега')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Login',
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default=None, max_length=20, unique=True, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_relate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tag_id', to='hakapp.Tag')),
                ('Worker_relate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Worker_id', to='hakapp.Worker')),
            ],
        ),
    ]
