# Generated by Django 2.2.5 on 2019-09-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakapp', '0003_auto_20190928_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Person',
            field=models.CharField(default='Григорий Голубев', max_length=255, verbose_name='Фамилия и имя пользователя'),
            preserve_default=False,
        ),
    ]
