# Generated by Django 2.2.5 on 2019-09-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakapp', '0004_user_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='Tags',
        ),
        migrations.AddField(
            model_name='worker',
            name='StartDate',
            field=models.DateField(default='1970-01-01', verbose_name='В компании с'),
            preserve_default=False,
        ),
    ]
