# Generated by Django 2.2.5 on 2019-09-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hakapp', '0007_worker_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True, verbose_name='Название профессии')),
            ],
        ),
        migrations.CreateModel(
            name='RelationProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prof_Relate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prof_id', to='hakapp.Profession')),
                ('Tag_relate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TagProfId', to='hakapp.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='RelationWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_relate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TagWorkId', to='hakapp.Tag')),
                ('Worker_relate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Worker_id', to='hakapp.Worker')),
            ],
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
