# Generated by Django 2.2.5 on 2019-09-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hakapp', '0008_auto_20190928_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='Progress',
        ),
    ]
