# Generated by Django 2.2.5 on 2019-09-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hakapp', '0010_relationprofession_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.IntegerField(verbose_name='Тип тега')),
                ('Profession_relate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prof_id', to='hakapp.Profession')),
                ('Tag_relate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tag_id', to='hakapp.Tag')),
                ('Worker_relate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Worker_id', to='hakapp.Worker')),
            ],
        ),
        migrations.RemoveField(
            model_name='relationworker',
            name='Tag_relate',
        ),
        migrations.RemoveField(
            model_name='relationworker',
            name='Worker_relate',
        ),
        migrations.DeleteModel(
            name='RelationProfession',
        ),
        migrations.DeleteModel(
            name='RelationWorker',
        ),
    ]
