# Generated by Django 2.2.5 on 2019-09-29 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hakapp', '0011_auto_20190928_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profession1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prof_id_from', to='hakapp.Profession')),
                ('Profession2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prof_id_to', to='hakapp.Profession')),
                ('TargetWorker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Worker_target_id', to='hakapp.Worker')),
            ],
        ),
    ]
