# Generated by Django 2.2.5 on 2019-09-29 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hakapp', '0012_retrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrain',
            name='TargetWorker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Worker_target_id', to='hakapp.Worker', unique=True),
        ),
    ]
